# Generated by Django 4.1.4 on 2022-12-28 17:13

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astronaut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('favorite_planet', models.CharField(max_length=100)),
                ('photo_url', models.TextField()),
                ('planets', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='no planets', max_length=100), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('preview_url', models.CharField(max_length=200, null=True)),
                ('astronaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='capstone.astronaut')),
            ],
        ),
    ]
