# Generated by Django 4.1.4 on 2022-12-27 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='ForumPost',
        ),
    ]
