# Generated by Django 4.1.4 on 2022-12-27 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_rename_post_forumpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForumPost',
        ),
    ]
