# Generated by Django 4.1.4 on 2022-12-28 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_alter_forum_astronaut_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='astronaut_id',
            new_name='astronaut',
        ),
    ]
