# Generated by Django 4.1.4 on 2022-12-27 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_delete_forumpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=100)),
                ('photo', models.CharField(default='no photo', max_length=100)),
                ('preview_url', models.CharField(max_length=200, null=True)),
                ('astronaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='capstone.astronaut')),
            ],
        ),
    ]
