# Generated by Django 4.1.4 on 2022-12-28 19:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_rename_astronaut_id_forum_astronaut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='planets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None),
        ),
    ]
