# Generated by Django 4.1.4 on 2022-12-28 19:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_alter_astronaut_planets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='planets',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default=['none'], max_length=100), size=None),
        ),
    ]
